@startuml カレーライスの作り方
title カレーライスの作り方
start
fork

:厚手の鍋にサラダ油を熱し、適当な大きさに切った牛肉、ニンジン、玉ねぎ、ジャガイモ、をよく炒めます。;
:水を加え、沸騰したらアクを取り、材料がやわらかくなるまで弱火-中火で煮込みます。;
:いったん火を止めてカレールウを割り入れ、充分に溶かし再び弱火で煮込みます。;


fork again
:炊飯器用のカップで米をはかり、ボウルに入れる。;
:ボウルにたっぷりの水を加え、手早く2～3回かき混ぜ、水を捨てる。これを3～4回ほど繰り返す。;
:炊飯器の釜に米を移し、目盛りまで水を加え、炊飯器にセットする。;

:炊き上がったらほぐす。;

end fork
:白飯をお皿に盛りつけ、カレーをかける。;
:カレーライス]
stop

@enduml