@startuml クラス図

class ライントレーサー{
   + 右旋回を始める(): void
   + 左旋回を始める(): void
   + 停止する():void
}

class 光センサー {
     明るさを取得する():void
}   

class 左モータ {
    動き始める():void
    停止する():void

}
class 右モータ {
    動き始める():void
    停止する():void
}

class CPU {
    + システムを制御する(): void
    + システムを起動する(): void
    + システムを停止する(): void
}

class 電源SW {
    + 電源を入れる()
    + 電源を切る()
}



ライントレーサー "1" -- "1" 光センサー
ライントレーサー "1"-- "1" 電源SW
ライントレーサー "1" -- "1" 左モータ
ライントレーサー "1" -- "1" 右モータ
ライントレーサー "1" -- "1" CPU


@enduml
