@startuml ホテルオブジェクト図


left to right direction

object "<u>ホテルUML</u>" as Hote {
部屋
}
object "<u>利用者情報:利用者A</u>" as C1 {
名前:三養基郡
住所:秋田県小林市
電話:080-2829-3224
}
object "<u>利用者情報:利用者B</u>" as C2 {
名前:竹本一馬
住所:秋田県大河原市
電話:080-7394-3343
}
object "<u>部屋情報1: 客室301号室</u>" as H1 {
タイプ:シングル
宿泊費:11,000円
キャンペーン価格:9000円
}
object "<u>部屋情報２: 客室302号室</u>" as H2 {
タイプ:シングル
宿泊費:11,000円
キャンペーン価格:9000円
}
object "<u>部屋情報3: 客室303号室</u>" as H3 {
タイプ:シングル
宿泊費:11,000円
キャンペーン価格:9000円
}
H1 -- Hote
H2 -- Hote
H3 -- Hote
Hote -- C1
Hote -- C2
@enduml