@startuml ステートマシン図
' left to right direction
skinparam monochrome true

[*] -> メニュー画面
メニュー画面 -> [*]
メニュー画面 -> 予約と確認画面 : 予約・確認


予約と確認画面 --> あなたの順番画面 : 登録[名前と電話番号を入力し登録ボタンを押す]
予約と確認画面 --> あなたの順番画面 : 確認[名前か電話番号を入力し確認ボタンを押す]
予約と確認画面 --> メニュー画面 : 取消[名前か電話番号を入力し取消ボタンを押す]


メニュー画面 -> 今の順番画面 : 表示
メニュー画面 <- 今の順番画面 : メニューへ戻る

メニュー画面 <- あなたの順番画面 :メニューへ戻る

@enduml
