@startuml 部屋
left to right direction
' skinparam monochrome true

[*] --> 空室状態

空室状態 --> 予約済状態 : 予約する[空席有り]
予約済状態 --> 使用状態 : 使用開始[チェックイン]
使用状態 --> 空室状態 : 使用終了[チェックアウト]
空室状態 -->[*]:予約しない[空室無し]

@enduml