@startuml ユースケース図
left to right direction


actor ユーザー as User
actor 看護士 as Nurse

rectangle "診察予約システム" {
  rectangle "予約を取り消す" as 取消
  rectangle "診察を予約する" as 予約
  rectangle "あなたの順番を確認する" as YourTurn
  rectangle "今の順番を確認する" as NowTurn
  


  User -- 取消
  User -- 予約 
  User -- YourTurn
  Nurse -up- NowTurn
  User -- NowTurn
}
@enduml
